### ISSUE TITLE
where do I find data_3d_h36m.npz for videopose3D?

### ISSUE THREAD

**Issue by no-Seaweed** [timtoronto634/CodingameUnleashtheGeek#1]
Hello, 

Thanks a lot for writing a blog on how to setup VideoPose3D.

I read in your blog that you should run the code below to get data_3d_h36m.npz

However, there was no code. 

Could you please either directly share the data_3d_h36m.npz or share the code that produces it?

I could not find it on the Web neither in VideoPose3D website.

Here is the issue I wrote in VideoPose3d https://github.com/facebookresearch/VideoPose3D/issues/97

and here is your blog about this:

https://qiita.com/timtoronto634/items/ee018ac89e6b9f779194

I apologize for contacting you here but I didn't find any other way of getting a hold of you.

**Comment by timtoronto634** [comment]
Hi,
thanks for reading the blog post.
You could leave a comment on the blog post for next time.
My code you mentioned is still on blog. I assume you wanted to say "there was no file.".
About the file, I am not sure if I am allowed to redistribute, so please wait for the official answer to the issue.
